### ISSUE TITLE
django-allauth 0.60 compatibility

### ISSUE THREAD

**Issue by torgeirl** [devilry/trix2#147]
Login with Trix 4.1.0 as of bac3ced01dcd5006225d3c93eb6ae52a8776fc1c (dev build) + django-allauth 0.60 lands the user on an error template:

![trix-4 1 0_login-failure](https://github.com/devilry/trix2/assets/796053/e3265ee7-b2c7-47ad-96d8-ff4b9517ff2a)

It does not yield a HTTP 500 and the login itself does work (ie. manually navigating to the front page your are logged in).

It does not happen with django-allauth 0.59.*, and it does not happen with Trix 4.0.0 + django-allauth 0.60. For all scenarios, the setting`SOCIALACCOUNT_OPENID_CONNECT_URL_PREFIX = ''` has been provided ([see Allauth's changelog for details](https://github.com/pennersr/django-allauth/blob/main/ChangeLog.rst)).

It might be related to #145.

**Comment by Levijatan** [comment]
I could not reproduce this error, but I have done some cleanup that might help in ae0d939. The `SOCIALACCOUNT_OPENID_CONNECT_URL_PREFIX = ''` should not have any effect since the url gets fetched directly from the provider. But if you could run a `python manage.py showurls` and see what the `dataporten_login` view url is set to with and without `SOCIALACCOUNT_OPENID_CONNECT_URL_PREFIX`?
